import 'package:flutter/material.dart';

enum ToggleStyle { rounded, square, minimal, flat, labeled, loading }

enum IconType { sun, morning, bulb, moon, night, star, none }

enum AnimationType { slide, fade, bounce, spring }

class SwitchConfig {
  double width;
  double height;
  double innerPadding;
  Color accentColor;
  Color thumbColor;
  Color borderColor;
  double borderRadius;
  bool innerShadow;
  bool transitionGlow;
  bool clickSound;
  AnimationType animation;
  ToggleStyle style;
  IconType lightIcon;
  IconType darkIcon;
  bool isOn;

  SwitchConfig({
    this.width = 64,
    this.height = 32,
    this.innerPadding = 3,
    this.accentColor = const Color(0xFF4F46E5),
    this.thumbColor = const Color(0xFFFFFFFF),
    this.borderColor = const Color(0xFF334155),
    this.borderRadius = 24,
    this.innerShadow = true,
    this.transitionGlow = false,
    this.clickSound = true,
    this.animation = AnimationType.slide,
    this.style = ToggleStyle.rounded,
    this.lightIcon = IconType.sun,
    this.darkIcon = IconType.moon,
    this.isOn = true,
  });

  SwitchConfig copyWith({
    double? width,
    double? height,
    double? innerPadding,
    Color? accentColor,
    Color? thumbColor,
    Color? borderColor,
    double? borderRadius,
    bool? innerShadow,
    bool? transitionGlow,
    bool? clickSound,
    AnimationType? animation,
    ToggleStyle? style,
    IconType? lightIcon,
    IconType? darkIcon,
    bool? isOn,
  }) {
    return SwitchConfig(
      width: width ?? this.width,
      height: height ?? this.height,
      innerPadding: innerPadding ?? this.innerPadding,
      accentColor: accentColor ?? this.accentColor,
      thumbColor: thumbColor ?? this.thumbColor,
      borderColor: borderColor ?? this.borderColor,
      borderRadius: borderRadius ?? this.borderRadius,
      innerShadow: innerShadow ?? this.innerShadow,
      transitionGlow: transitionGlow ?? this.transitionGlow,
      clickSound: clickSound ?? this.clickSound,
      animation: animation ?? this.animation,
      style: style ?? this.style,
      lightIcon: lightIcon ?? this.lightIcon,
      darkIcon: darkIcon ?? this.darkIcon,
      isOn: isOn ?? this.isOn,
    );
  }

  String colorToHex(Color color) {
    return '#${color.value.toRadixString(16).substring(2).toUpperCase()}';
  }

  String generateFlutterCode() {
    return '''
// Custom Toggle Switch Widget
// Generated by Switch Creation Tool

import 'package:flutter/material.dart';

class CustomToggleSwitch extends StatefulWidget {
  final bool initialValue;
  final ValueChanged<bool>? onChanged;

  const CustomToggleSwitch({
    super.key,
    this.initialValue = false,
    this.onChanged,
  });

  @override
  State<CustomToggleSwitch> createState() => _CustomToggleSwitchState();
}

class _CustomToggleSwitchState extends State<CustomToggleSwitch>
    with SingleTickerProviderStateMixin {
  late bool _isOn;
  late AnimationController _controller;
  late Animation<double> _slideAnimation;

  @override
  void initState() {
    super.initState();
    _isOn = widget.initialValue;
    _controller = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 250),
      value: _isOn ? 1.0 : 0.0,
    );
    _slideAnimation = CurvedAnimation(
      parent: _controller,
      curve: Curves.easeInOut,
    );
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  void _toggle() {
    setState(() {
      _isOn = !_isOn;
      if (_isOn) {
        _controller.forward();
      } else {
        _controller.reverse();
      }
    });
    widget.onChanged?.call(_isOn);
  }

  @override
  Widget build(BuildContext context) {
    final double width = ${width.toStringAsFixed(0)};
    final double height = ${height.toStringAsFixed(0)};
    final double padding = ${innerPadding.toStringAsFixed(1)};
    final double thumbSize = height - padding * 2;
    final double borderRadius = ${borderRadius.toStringAsFixed(0)};

    return GestureDetector(
      onTap: _toggle,
      child: AnimatedBuilder(
        animation: _slideAnimation,
        builder: (context, child) {
          return Container(
            width: width,
            height: height,
            decoration: BoxDecoration(
              color: Color.lerp(
                const Color(0xFF${borderColor.value.toRadixString(16).substring(2).toUpperCase()}),
                const Color(0xFF${accentColor.value.toRadixString(16).substring(2).toUpperCase()}),
                _slideAnimation.value,
              ),
              borderRadius: BorderRadius.circular(borderRadius.toDouble()),
              border: Border.all(
                color: const Color(0xFF${borderColor.value.toRadixString(16).substring(2).toUpperCase()}),
                width: 1,
              ),
              boxShadow: ${innerShadow ? '''[
                BoxShadow(
                  color: Colors.black.withOpacity(0.3),
                  blurRadius: 4,
                  offset: const Offset(0, 2),
                ),
              ]''' : '[]'},
            ),
            child: Stack(
              alignment: Alignment.centerLeft,
              children: [
                Positioned(
                  left: padding +
                      _slideAnimation.value *
                          (width - thumbSize - padding * 2),
                  child: Container(
                    width: thumbSize,
                    height: thumbSize,
                    decoration: BoxDecoration(
                      color: const Color(0xFF${thumbColor.value.toRadixString(16).substring(2).toUpperCase()}),
                      borderRadius: BorderRadius.circular(borderRadius.toDouble()),
                      boxShadow: [
                        BoxShadow(
                          color: Colors.black.withOpacity(0.2),
                          blurRadius: 4,
                          offset: const Offset(0, 2),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          );
        },
      ),
    );
  }
}

// Usage:
// CustomToggleSwitch(
//   initialValue: false,
//   onChanged: (value) {
//     print('Switch is: \$value');
//   },
// )
''';
  }

  String generateCssCode() {
    return '''
/* Custom Toggle Switch - CSS */
/* Generated by Switch Creation Tool */

.toggle-switch {
  position: relative;
  display: inline-block;
  width: ${width.toInt()}px;
  height: ${height.toInt()}px;
}

.toggle-switch input {
  opacity: 0;
  width: 0;
  height: 0;
}

.toggle-slider {
  position: absolute;
  cursor: pointer;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: ${colorToHex(borderColor)};
  border: 1px solid ${colorToHex(borderColor)};
  transition: 0.25s ease-in-out;
  border-radius: ${borderRadius.toInt()}px;
  ${innerShadow ? 'box-shadow: inset 0 2px 4px rgba(0,0,0,0.3);' : ''}
}

.toggle-slider:before {
  position: absolute;
  content: "";
  height: ${(height - innerPadding * 2).toInt()}px;
  width: ${(height - innerPadding * 2).toInt()}px;
  left: ${innerPadding.toInt()}px;
  bottom: ${innerPadding.toInt()}px;
  background-color: ${colorToHex(thumbColor)};
  transition: 0.25s ease-in-out;
  border-radius: ${borderRadius.toInt()}px;
  box-shadow: 0 2px 4px rgba(0,0,0,0.2);
}

input:checked + .toggle-slider {
  background-color: ${colorToHex(accentColor)};
  border-color: ${colorToHex(accentColor)};
  ${transitionGlow ? 'box-shadow: 0 0 8px ${colorToHex(accentColor)}66;' : ''}
}

input:checked + .toggle-slider:before {
  transform: translateX(${(width - (height - innerPadding * 2) - innerPadding * 2).toInt()}px);
}

/* HTML Usage:
<label class="toggle-switch">
  <input type="checkbox">
  <span class="toggle-slider"></span>
</label>
*/
''';
  }
}

class SavedSwitch {
  final String name;
  final SwitchConfig config;
  final DateTime editedAt;

  SavedSwitch({
    required this.name,
    required this.config,
    required this.editedAt,
  });
}
